# Generated by Django 3.2.3 on 2022-05-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataFaker', '0002_alter_datafakerrecordinfo_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafakerrecordinfo',
            name='count',
            field=models.IntegerField(default=-1, null=True, verbose_name='数据条数'),
        ),
    ]
