# Generated by Django 3.2.3 on 2022-05-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataFaker', '0004_alter_datafakerrecordinfo_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafakerrecordinfo',
            name='count',
            field=models.IntegerField(auto_created=True, default=-1, verbose_name='数据条数'),
        ),
    ]
