# Generated by Django 4.0.4 on 2024-04-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataFaker', '0006_alter_datafakerrecordinfo_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafakerrecordinfo',
            name='user',
            field=models.IntegerField(null=True, verbose_name='文件上传所属用户'),
        ),
    ]
