# Generated by Django 3.2.3 on 2021-10-02 10:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=256, verbose_name='项目名称')),
                ('summary', models.TextField(null=True, verbose_name='项目描述')),
                ('url', models.CharField(max_length=128, verbose_name='项目地址')),
                ('status', models.CharField(choices=[('dev', 'development'), ('finish', 'finish')], default='dev', max_length=32, verbose_name='项目状态')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'projects',
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AlterModelOptions(
            name='sitescomments',
            options={'verbose_name': '网站留言', 'verbose_name_plural': '网站留言'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': '类别', 'verbose_name_plural': '类别'},
        ),
        migrations.RemoveField(
            model_name='sitescomments',
            name='address',
        ),
        migrations.AddField(
            model_name='sitescomments',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='调用的IP地址'),
        ),
        migrations.AddField(
            model_name='sitescomments',
            name='loc_city',
            field=models.CharField(max_length=256, null=True, verbose_name='调用地址(城市)'),
        ),
        migrations.AddField(
            model_name='sitescomments',
            name='loc_country',
            field=models.CharField(max_length=256, null=True, verbose_name='调用地址(国家)'),
        ),
        migrations.AddField(
            model_name='sitescomments',
            name='loc_province',
            field=models.CharField(max_length=256, null=True, verbose_name='调用地址(省份)'),
        ),
        migrations.AddField(
            model_name='tags',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 2, 10, 19, 58, 175084, tzinfo=utc), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='type',
            field=models.CharField(choices=[('article', 'article'), ('project', 'project')], default='article', max_length=64, verbose_name='标签对应的模型'),
        ),
        migrations.AddField(
            model_name='tags',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='types',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 2, 10, 20, 11, 969832, tzinfo=utc), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='types',
            name='pid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.types', verbose_name='父级分类'),
        ),
        migrations.AddField(
            model_name='types',
            name='type',
            field=models.CharField(choices=[('article', 'article'), ('project', 'project')], default='article', max_length=64, verbose_name='类别对应的模型'),
        ),
        migrations.AddField(
            model_name='types',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterModelTable(
            name='tags',
            table='article_tags',
        ),
        migrations.AlterModelTable(
            name='types',
            table='types',
        ),
    ]
