# Generated by Django 3.2.3 on 2021-10-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211002_1820'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tags',
            table='tags',
        ),
    ]
