# Generated by Django 3.2.3 on 2021-10-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_tags_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='backgroundmusic',
            table='back_music',
        ),
        migrations.AlterModelTable(
            name='friendslink',
            table='friends_links',
        ),
        migrations.AlterModelTable(
            name='homepictures',
            table='home_back_pic',
        ),
        migrations.AlterModelTable(
            name='sitescomments',
            table='site_comments',
        ),
    ]
