# Generated by Django 3.2.3 on 2021-10-02 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20211002_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='next',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_article', to='articles.article', verbose_name='下一篇文章'),
        ),
        migrations.AddField(
            model_name='article',
            name='pre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_article', to='articles.article', verbose_name='上一篇文章'),
        ),
    ]
