# Generated by Django 3.2.3 on 2021-10-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20211002_2245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SitesComments',
        ),
    ]
