# Generated by Django 3.2.3 on 2021-10-05 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_articlecomments_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackGroundMusic',
        ),
        migrations.DeleteModel(
            name='FriendsLink',
        ),
        migrations.DeleteModel(
            name='HomePictures',
        ),
    ]
