# Generated by Django 4.0.4 on 2022-11-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20211005_1237'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='blog_articles',
        ),
        migrations.AlterModelTable(
            name='articlecomments',
            table='blog_article_comments',
        ),
        migrations.AlterModelTable(
            name='projects',
            table='site_projects',
        ),
        migrations.AlterModelTable(
            name='tags',
            table='blog_tags',
        ),
        migrations.AlterModelTable(
            name='types',
            table='blog_types',
        ),
    ]
