# Generated by Django 4.0.4 on 2022-08-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrlRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('url', models.URLField(help_text='url', verbose_name='url')),
                ('short_flag', models.CharField(default='undefined', help_text='短链接', max_length=64, null=True, verbose_name='短链接')),
                ('description', models.TextField(help_text='描述', null=True, verbose_name='url描述')),
                ('type', models.CharField(choices=[('self', 'self'), ('xl', 'xl'), ('tx', 'tx')], default='self', max_length=16, verbose_name='类别对应的模型')),
                ('expire_time', models.DateTimeField(help_text='过期时间', verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '短链接记录',
                'verbose_name_plural': '短链接记录',
                'db_table': 'short_uri_records',
                'unique_together': {('type', 'url')},
            },
        ),
    ]
