# Generated by Django 4.0.4 on 2024-03-25 16:53

from django.db import migrations, models
import thirdApis.models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdApis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptmessage',
            name='error_code',
            field=models.CharField(blank=True, help_text='错误代码', max_length=64, null=True, verbose_name='错误代码'),
        ),
        migrations.AlterField(
            model_name='gptmessage',
            name='error_detail',
            field=models.CharField(blank=True, help_text='错误详情', max_length=256, null=True, verbose_name='错误详情'),
        ),
        migrations.AlterField(
            model_name='gptmessage',
            name='interrupt_reason',
            field=models.CharField(blank=True, help_text='停止类型', max_length=16, null=True, verbose_name='停止类型'),
        ),
        migrations.AlterField(
            model_name='gptmessage',
            name='reply_content',
            field=models.TextField(blank=True, help_text='回复内容', null=True, verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='gptmessage',
            name='websocket_id',
            field=models.CharField(db_index=True, default=thirdApis.models.get_uuid, help_text='该次对话对应的websocketID', max_length=64, verbose_name='websocketID'),
        ),
    ]
