# Generated by Django 4.0.4 on 2024-03-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdApis', '0002_alter_gptmessage_error_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptconversation',
            name='key',
            field=models.CharField(default='', help_text='当前会话使用的API KEY', max_length=256, verbose_name='API-KEY'),
        ),
    ]
