# Generated by Django 4.0.4 on 2023-02-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdApis', '0002_remove_chatgptmessage_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptmessage',
            name='conversation_uuid',
            field=models.UUIDField(default=11, help_text='所属会话ID', verbose_name='所属会话ID'),
            preserve_default=False,
        ),
    ]
