# Generated by Django 4.0.4 on 2022-10-29 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdApis', '0002_apicollector'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicollector',
            name='api_price',
            field=models.FloatField(default=0.0, help_text='Api价格', verbose_name='Api价格'),
        ),
        migrations.AddField(
            model_name='apicollector',
            name='api_price_unit',
            field=models.CharField(default=0.0, help_text='Api价格单位', max_length=64, verbose_name='Api价格单位'),
        ),
        migrations.AlterField(
            model_name='apicollector',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 0, 11, 45, 2085), help_text='过期时间', verbose_name='过期时间'),
        ),
    ]
