# Generated by Django 4.0.4 on 2024-03-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdApis', '0003_gptconversation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptconversation',
            name='platform',
            field=models.CharField(choices=[('chatGpt', 'chatGpt'), ('通义千问', '通义千问')], help_text='平台名称', max_length=64, verbose_name='平台名称'),
        ),
    ]
