# Generated by Django 4.0.4 on 2023-02-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdApis', '0003_chatgptmessage_conversation_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgptmessage',
            name='conversation_uuid',
        ),
        migrations.AddField(
            model_name='chatgptmessage',
            name='conversation_id',
            field=models.SmallIntegerField(default=1, help_text='所属会话ID', verbose_name='所属会话ID'),
            preserve_default=False,
        ),
    ]
