# Generated by Django 4.0.4 on 2022-10-30 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdApis', '0003_apicollector_api_price_apicollector_api_price_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCollectorSpiderRunRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('pid', models.SmallIntegerField(default='unknown', help_text='脚本运行的进程ID', verbose_name='脚本运行的进程ID')),
                ('log_path', models.CharField(help_text='脚本运行的日志地址', max_length=128, verbose_name='脚本运行的日志地址')),
                ('finish_time', models.DateTimeField(default=datetime.datetime(2022, 10, 30, 15, 4, 49, 699094), help_text='完成时间', verbose_name='完成时间')),
                ('result', models.SmallIntegerField(default=2, help_text='脚本运行结果,成功为0,异常为1,正在运行为2', verbose_name='脚本运行结果,成功为0,异常为1，正在运行为2')),
            ],
            options={
                'verbose_name': 'apiSpider执行记录',
                'verbose_name_plural': 'apiSpider执行记录',
                'db_table': 'ac_spider_run_record',
            },
        ),
        migrations.AlterField(
            model_name='apicollector',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 15, 4, 49, 699094), help_text='过期时间', verbose_name='过期时间'),
        ),
    ]
