# Generated by Django 4.0.4 on 2024-03-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdApis', '0004_alter_gptconversation_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptconversation',
            name='deleted',
            field=models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除'),
        ),
    ]
