# Generated by Django 4.0.4 on 2022-10-31 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdApis', '0005_alter_apicollector_expire_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicollectorspiderrunrecord',
            options={'permissions': [('view_apicollector', 'add_apicollector')], 'verbose_name': 'apiSpider执行记录', 'verbose_name_plural': 'apiSpider执行记录'},
        ),
        migrations.AlterField(
            model_name='apicollector',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 15, 27, 32, 615240), help_text='过期时间', verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='apicollectorspiderrunrecord',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 15, 27, 32, 615240), help_text='完成时间', verbose_name='完成时间'),
        ),
    ]
