# Generated by Django 4.0.4 on 2022-10-31 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdApis', '0006_alter_apicollectorspiderrunrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicollector',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 22, 40, 41, 923406), help_text='过期时间', verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='apicollectorspiderrunrecord',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 22, 40, 41, 924409), help_text='完成时间', verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='apicollectorspiderrunrecord',
            name='pid',
            field=models.IntegerField(default='unknown', help_text='脚本运行的进程ID', verbose_name='脚本运行的进程ID'),
        ),
    ]
