# Generated by Django 4.0.4 on 2022-11-01 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdApis', '0008_alter_apicollectorspiderrunrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicollector',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 17, 41, 55, 585892), help_text='过期时间', verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='apicollectorspiderrunrecord',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 17, 41, 55, 585892), help_text='完成时间', verbose_name='完成时间'),
        ),
    ]
