# Generated by Django 4.0.4 on 2022-11-01 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdApis', '0010_alter_apicollector_expire_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicollector',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 9, 1, 0, 7, 808665), help_text='过期时间', verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='apicollectorspiderrunrecord',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 1, 0, 7, 808665), help_text='完成时间', verbose_name='完成时间'),
        ),
    ]
