# Generated by Django 4.0.4 on 2022-11-02 16:06

import datetime
from django.db import migrations, models
import thirdApis.models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdApis', '0022_alter_apicollector_expire_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicollector',
            name='expire_time',
            field=models.DateTimeField(default=thirdApis.models.default_expire_time, help_text='过期时间', verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='apicollectorspiderrunrecord',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='完成时间', verbose_name='完成时间'),
        ),
    ]
