# Generated by Django 4.0.4 on 2022-11-07 07:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thirdApis', '0024_apicollectorspiderrunrecord_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicollectorspiderrunrecord',
            name='invoker',
            field=models.ForeignKey(default=1, help_text='调用者', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='调用者'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ApiCollectorSpiderResourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(help_text='脚本名称', max_length=128, unique=True, verbose_name='脚本名称')),
                ('script_path', models.CharField(help_text='脚本储存路径', max_length=128, verbose_name='脚本储存路径')),
                ('last_run_time', models.DateTimeField(default=datetime.datetime.now, help_text='上次运行时间', verbose_name='上次运行时间')),
                ('run_count', models.PositiveIntegerField(default=0, help_text='运行次数', verbose_name='运行次数')),
                ('is_forbidden', models.BooleanField(default=False, help_text='该脚本是否被禁用', verbose_name='该脚本是否被禁用')),
                ('user', models.ForeignKey(help_text='创建者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'apiSpider可用资源',
                'verbose_name_plural': 'apiSpider可用资源',
                'db_table': 'ac_spider_resource',
            },
        ),
    ]
