# Generated by Django 4.0.4 on 2022-11-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdApis', '0025_apicollectorspiderrunrecord_invoker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicollectorspiderresourcemodel',
            name='run_command',
            field=models.CharField(default='echo no-command', help_text='运行指令', max_length=128, verbose_name='运行指令'),
        ),
        migrations.AddField(
            model_name='apicollectorspiderrunrecord',
            name='unique_flag',
            field=models.CharField(default=1, help_text='脚本运行记录唯一标识', max_length=128, verbose_name='脚本运行记录唯一标识'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='apicollector',
            table='ac_info_set',
        ),
    ]
