# Generated by Django 4.0.4 on 2022-11-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdApis', '0026_apicollectorspiderresourcemodel_run_command_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicollectorspiderresourcemodel',
            name='last_run_time',
            field=models.DateTimeField(help_text='上次运行时间', null=True, verbose_name='上次运行时间'),
        ),
    ]
