# Generated by Django 4.0.4 on 2022-11-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdApis', '0029_remove_apicollectorspiderresourcemodel_run_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicollectorspiderresourcemodel',
            name='run_command',
            field=models.CharField(default='echo no-command', help_text='运行指令', max_length=128, verbose_name='运行指令'),
        ),
    ]
