# Generated by Django 4.0.4 on 2022-11-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdApis', '0030_apicollectorspiderresourcemodel_run_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicollectorspiderresourcemodel',
            name='run_command',
            field=models.CharField(help_text='运行指令', max_length=256, null=True, verbose_name='运行指令'),
        ),
    ]
