# Generated by Django 4.0.4 on 2022-11-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdApis', '0031_alter_apicollectorspiderresourcemodel_run_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicollectorspiderrunrecord',
            name='run_command',
            field=models.TextField(default='echo no-command', help_text='运行命令', verbose_name='运行命令'),
        ),
    ]
