# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gpt.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tgpt.proto\x12\x06GptApp\"\xb1\x01\n\x18UpdateQueryResultRequest\x12\x15\n\rreply_content\x18\x01 \x01(\t\x12\x18\n\x10query_message_id\x18\x02 \x01(\t\x12\x11\n\tinterrupt\x18\x03 \x01(\x08\x12\x18\n\x10interrupt_reason\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\x08\x12\x12\n\nerror_code\x18\x06 \x01(\t\x12\x14\n\x0c\x65rror_detail\x18\x07 \x01(\t\")\n\x16UpdateQueryResultReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"d\n$UpdateDataFakerGenerateResultRequest\x12\x12\n\nrecord_key\x18\x01 \x01(\t\x12\x11\n\tfile_path\x18\x02 \x01(\t\x12\x15\n\rdownload_code\x18\x03 \x01(\t\"5\n\"UpdateDataFakerGenerateResultReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xe2\x01\n\nGptMessage\x12W\n\x11UpdateQueryResult\x12 .GptApp.UpdateQueryResultRequest\x1a\x1e.GptApp.UpdateQueryResultReply\"\x00\x12{\n\x1dUpdateDataFakerGenerateResult\x12,.GptApp.UpdateDataFakerGenerateResultRequest\x1a*.GptApp.UpdateDataFakerGenerateResultReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gpt_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPDATEQUERYRESULTREQUEST']._serialized_start=22
  _globals['_UPDATEQUERYRESULTREQUEST']._serialized_end=199
  _globals['_UPDATEQUERYRESULTREPLY']._serialized_start=201
  _globals['_UPDATEQUERYRESULTREPLY']._serialized_end=242
  _globals['_UPDATEDATAFAKERGENERATERESULTREQUEST']._serialized_start=244
  _globals['_UPDATEDATAFAKERGENERATERESULTREQUEST']._serialized_end=344
  _globals['_UPDATEDATAFAKERGENERATERESULTREPLY']._serialized_start=346
  _globals['_UPDATEDATAFAKERGENERATERESULTREPLY']._serialized_end=399
  _globals['_GPTMESSAGE']._serialized_start=402
  _globals['_GPTMESSAGE']._serialized_end=628
# @@protoc_insertion_point(module_scope)
