# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gpt.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gpt.proto',
  package='GptApp',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tgpt.proto\x12\x06GptApp\"\xb1\x01\n\x18UpdateQueryResultRequest\x12\x15\n\rreply_content\x18\x01 \x01(\t\x12\x18\n\x10query_message_id\x18\x02 \x01(\t\x12\x11\n\tinterrupt\x18\x03 \x01(\x08\x12\x18\n\x10interrupt_reason\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\x08\x12\x12\n\nerror_code\x18\x06 \x01(\t\x12\x14\n\x0c\x65rror_detail\x18\x07 \x01(\t\")\n\x16UpdateQueryResultReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x65\n\nGptMessage\x12W\n\x11UpdateQueryResult\x12 .GptApp.UpdateQueryResultRequest\x1a\x1e.GptApp.UpdateQueryResultReply\"\x00\x62\x06proto3'
)




_UPDATEQUERYRESULTREQUEST = _descriptor.Descriptor(
  name='UpdateQueryResultRequest',
  full_name='GptApp.UpdateQueryResultRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply_content', full_name='GptApp.UpdateQueryResultRequest.reply_content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='query_message_id', full_name='GptApp.UpdateQueryResultRequest.query_message_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interrupt', full_name='GptApp.UpdateQueryResultRequest.interrupt', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interrupt_reason', full_name='GptApp.UpdateQueryResultRequest.interrupt_reason', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='GptApp.UpdateQueryResultRequest.error', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='GptApp.UpdateQueryResultRequest.error_code', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_detail', full_name='GptApp.UpdateQueryResultRequest.error_detail', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=199,
)


_UPDATEQUERYRESULTREPLY = _descriptor.Descriptor(
  name='UpdateQueryResultReply',
  full_name='GptApp.UpdateQueryResultReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='GptApp.UpdateQueryResultReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=242,
)

DESCRIPTOR.message_types_by_name['UpdateQueryResultRequest'] = _UPDATEQUERYRESULTREQUEST
DESCRIPTOR.message_types_by_name['UpdateQueryResultReply'] = _UPDATEQUERYRESULTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateQueryResultRequest = _reflection.GeneratedProtocolMessageType('UpdateQueryResultRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEQUERYRESULTREQUEST,
  '__module__' : 'gpt_pb2'
  # @@protoc_insertion_point(class_scope:GptApp.UpdateQueryResultRequest)
  })
_sym_db.RegisterMessage(UpdateQueryResultRequest)

UpdateQueryResultReply = _reflection.GeneratedProtocolMessageType('UpdateQueryResultReply', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEQUERYRESULTREPLY,
  '__module__' : 'gpt_pb2'
  # @@protoc_insertion_point(class_scope:GptApp.UpdateQueryResultReply)
  })
_sym_db.RegisterMessage(UpdateQueryResultReply)



_GPTMESSAGE = _descriptor.ServiceDescriptor(
  name='GptMessage',
  full_name='GptApp.GptMessage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=244,
  serialized_end=345,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateQueryResult',
    full_name='GptApp.GptMessage.UpdateQueryResult',
    index=0,
    containing_service=None,
    input_type=_UPDATEQUERYRESULTREQUEST,
    output_type=_UPDATEQUERYRESULTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GPTMESSAGE)

DESCRIPTOR.services_by_name['GptMessage'] = _GPTMESSAGE

# @@protoc_insertion_point(module_scope)
