# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import gpt_pb2 as gpt__pb2


class GptMessageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateQueryResult = channel.unary_unary(
                '/GptApp.GptMessage/UpdateQueryResult',
                request_serializer=gpt__pb2.UpdateQueryResultRequest.SerializeToString,
                response_deserializer=gpt__pb2.UpdateQueryResultReply.FromString,
                )
        self.UpdateDataFakerGenerateResult = channel.unary_unary(
                '/GptApp.GptMessage/UpdateDataFakerGenerateResult',
                request_serializer=gpt__pb2.UpdateDataFakerGenerateResultRequest.SerializeToString,
                response_deserializer=gpt__pb2.UpdateDataFakerGenerateResultReply.FromString,
                )


class GptMessageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateQueryResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDataFakerGenerateResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GptMessageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateQueryResult': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateQueryResult,
                    request_deserializer=gpt__pb2.UpdateQueryResultRequest.FromString,
                    response_serializer=gpt__pb2.UpdateQueryResultReply.SerializeToString,
            ),
            'UpdateDataFakerGenerateResult': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDataFakerGenerateResult,
                    request_deserializer=gpt__pb2.UpdateDataFakerGenerateResultRequest.FromString,
                    response_serializer=gpt__pb2.UpdateDataFakerGenerateResultReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GptApp.GptMessage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GptMessage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateQueryResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GptApp.GptMessage/UpdateQueryResult',
            gpt__pb2.UpdateQueryResultRequest.SerializeToString,
            gpt__pb2.UpdateQueryResultReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateDataFakerGenerateResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GptApp.GptMessage/UpdateDataFakerGenerateResult',
            gpt__pb2.UpdateDataFakerGenerateResultRequest.SerializeToString,
            gpt__pb2.UpdateDataFakerGenerateResultReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
