# Generated by Django 3.2.3 on 2022-04-16 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filebroker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('value', models.CharField(max_length=128, verbose_name='文件名')),
            ],
            options={
                'verbose_name': 'test',
                'verbose_name_plural': 'test',
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('file_key', models.CharField(db_index=True, max_length=255, verbose_name='文件唯一标识')),
                ('file_name', models.CharField(max_length=128, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(null=True, verbose_name='文件大小(kb)')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('expire_time', models.DateTimeField(verbose_name='过期时间')),
                ('file', models.FileField(max_length=255, null=True, upload_to=filebroker.models.file_directory_path)),
                ('md5', models.CharField(db_index=True, max_length=255, null=True, verbose_name='文件MD5')),
                ('is_upload_finish', models.BooleanField(default=False, verbose_name='是否已经上传完成')),
                ('is_last', models.BooleanField(default=False, verbose_name='是否为最后一个切片')),
                ('chunk_num', models.SmallIntegerField(default=0, verbose_name='文件切片序号')),
                ('chunk_count', models.IntegerField(verbose_name='文件切片总数')),
                ('download_code', models.CharField(max_length=255, null=True, verbose_name='文件下载码')),
                ('is_merge', models.BooleanField(default=False, verbose_name='是否已经合并')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='文件上传所属用户')),
            ],
            options={
                'verbose_name': '文件信息表',
                'verbose_name_plural': '文件信息表',
                'db_table': 'file_info',
            },
        ),
        migrations.CreateModel(
            name='DownLoadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('down_code', models.CharField(max_length=255, null=True, verbose_name='文件下载码')),
                ('down_finish', models.BooleanField(default=False, verbose_name='是否下载完成')),
                ('down_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filebroker.fileinfo', verbose_name='下载的文件')),
            ],
            options={
                'verbose_name': '下载记录表',
                'verbose_name_plural': '下载记录表',
                'db_table': 'download_record',
            },
        ),
    ]
