# Generated by Django 3.2.3 on 2021-10-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('is_custom', models.BooleanField(default=False, verbose_name='是否为用户自定义')),
            ],
            options={
                'verbose_name': '毒鸡汤',
                'verbose_name_plural': '毒鸡汤',
                'db_table': 'drug_words',
            },
        ),
    ]
