# Generated by Django 3.2.7 on 2022-04-01 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdOauthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('oauth_type', models.SmallIntegerField(choices=[(1, 'qq'), (2, 'wechat'), (3, 'weibo'), (4, 'github'), (5, 'gitee')], max_length=4, verbose_name='第三方登录类型')),
                ('oauth_id', models.IntegerField(max_length=64, verbose_name='用户ID')),
                ('oauth_count', models.CharField(blank=True, max_length=128, null=True, verbose_name='登陆的账户')),
                ('oauth_phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='手机号')),
                ('oauth_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='登录的邮箱')),
                ('oauth_avatar_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='头像链接url')),
                ('is_bind', models.BooleanField(default=False, verbose_name='是否已经绑定账户')),
                ('user', models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_oauth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '第三方登录信息表',
                'verbose_name_plural': '第三方登录信息表',
                'db_table': 'third_auth_info',
            },
        ),
    ]
