# Generated by Django 3.2.7 on 2022-04-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_thirdoauthinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdoauthinfo',
            name='oauth_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='登录用户名'),
        ),
        migrations.AlterField(
            model_name='thirdoauthinfo',
            name='oauth_id',
            field=models.IntegerField(verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='thirdoauthinfo',
            name='oauth_type',
            field=models.SmallIntegerField(choices=[(1, 'qq'), (2, 'wechat'), (3, 'weibo'), (4, 'github'), (5, 'gitee')], verbose_name='第三方登录类型'),
        ),
    ]
