# Generated by Django 4.0.4 on 2022-11-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220401_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='userrolemembership',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrolemembership',
            name='userprofile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserRoleMemberShip',
        ),
    ]
