# Generated by Django 3.2.3 on 2021-10-05 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('update_content', models.TextField(verbose_name='更新内容')),
                ('is_finish', models.BooleanField(default=True, verbose_name='完成')),
                ('finish_time', models.DateTimeField(verbose_name='完成时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '更新日志',
                'verbose_name_plural': '更新日志',
                'db_table': 'update_log',
            },
        ),
    ]
