# Generated by Django 3.2.3 on 2021-10-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackGroundMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('musicId', models.CharField(max_length=64, unique=True, verbose_name='音乐ID')),
                ('title', models.CharField(default='随机播放的音乐', max_length=64, verbose_name='歌名')),
                ('name', models.CharField(default='UNKNOWN', max_length=64, verbose_name='作者')),
                ('type', models.CharField(default='UNKNOWN', max_length=64, verbose_name='类型')),
                ('url', models.CharField(max_length=128, verbose_name='音乐源')),
                ('avatar', models.CharField(max_length=128, verbose_name='缩略图保存的本地路径')),
                ('is_user', models.BooleanField(default=True, verbose_name='是否允许使用')),
            ],
            options={
                'verbose_name': '背景音乐',
                'verbose_name_plural': '背景音乐合集',
                'db_table': 'back_music',
            },
        ),
        migrations.CreateModel(
            name='FriendsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('site', models.CharField(help_text='url 链接', max_length=256, verbose_name='url链接')),
                ('title', models.CharField(max_length=64, verbose_name='链接名称')),
                ('intro', models.CharField(max_length=128, verbose_name='一句话介绍')),
                ('cover', models.ImageField(blank=True, upload_to='blog/friendsLinkCover/%Y%m%d/', verbose_name='链接封面')),
                ('author', models.CharField(default='不愿意透露姓名的小伙', max_length=64, verbose_name='作者')),
                ('is_show', models.BooleanField(default=True, verbose_name='允许显示')),
            ],
            options={
                'verbose_name': '伙伴链接',
                'verbose_name_plural': '伙伴连接',
                'db_table': 'friends_links',
            },
        ),
        migrations.CreateModel(
            name='HomePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('path', models.CharField(help_text='主页图片路径', max_length=128, verbose_name='图片路径')),
                ('is_able', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '网站主页照片显示',
                'verbose_name_plural': '网站主页照片显示',
                'db_table': 'home_back_pic',
            },
        ),
    ]
