# Generated by Django 3.2.3 on 2021-10-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sitecomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendslink',
            name='cover',
            field=models.CharField(blank=True, max_length=256, verbose_name='链接封面'),
        ),
    ]
