# Generated by Django 4.0.4 on 2022-11-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_friendslink_cover'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='backgroundmusic',
            table='site_back_music',
        ),
        migrations.AlterModelTable(
            name='friendslink',
            table='site_friends_links',
        ),
        migrations.AlterModelTable(
            name='homepictures',
            table='site_back_pic',
        ),
        migrations.AlterModelTable(
            name='updatelog',
            table='site_update_log',
        ),
    ]
