# Generated by Django 4.0.4 on 2023-08-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_sitecomments_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecomments',
            name='avatar',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='头像链接'),
        ),
        migrations.AddField(
            model_name='sitecomments',
            name='gender',
            field=models.SmallIntegerField(default=0, verbose_name='性别'),
        ),
    ]
