# Generated by Django 4.0.4 on 2023-08-12 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_sitecomments_avatar_sitecomments_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecomments',
            name='replay_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sitecomment_replay_to', to='home.sitecomments'),
        ),
    ]
