# Generated by Django 4.0.4 on 2023-08-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_sitecomments_replay_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecomments',
            name='root_id',
            field=models.IntegerField(default=-1, help_text='根评论ID(-1表示父节点)', verbose_name='根评论ID'),
        ),
    ]
