# Generated by Django 4.0.4 on 2023-08-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_sitecomments_root_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatelog',
            name='author',
        ),
        migrations.AddField(
            model_name='updatelog',
            name='repo_uri',
            field=models.CharField(max_length=256, null=True, verbose_name='仓库地址'),
        ),
        migrations.AddField(
            model_name='updatelog',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='用户ID'),
        ),
        migrations.AddField(
            model_name='updatelog',
            name='user_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='用户名称'),
        ),
    ]
