# Generated by Django 4.0.4 on 2023-09-05 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_updatelog_update_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatelog',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='完成时间'),
        ),
    ]
