# Generated by Django 4.0.4 on 2024-08-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_homepictures_backgroundimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimages',
            name='md5',
            field=models.CharField(default='', max_length=256, verbose_name='md5'),
        ),
    ]
