# Generated by Django 4.0.4 on 2024-08-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_backgroundimages_md5'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimages',
            name='file_name',
            field=models.CharField(default='', max_length=256, verbose_name='文件名'),
            preserve_default=False,
        ),
    ]
