# Generated by Django 4.0.4 on 2022-11-10 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('group_name', models.CharField(help_text='用户组名称', max_length=128, verbose_name='用户组名称')),
                ('p_id', models.IntegerField(default=-1, help_text='父用户组名称', verbose_name='父用户组名称')),
            ],
            options={
                'verbose_name': 'rbac_用户组',
                'verbose_name_plural': 'rbac_用户组',
                'db_table': 'rbac_group',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('role_name', models.CharField(help_text='用户角色', max_length=128, unique=True, verbose_name='用户角色')),
            ],
            options={
                'verbose_name': 'rbac_用户角色',
                'verbose_name_plural': 'rbac_用户角色',
                'db_table': 'rbac_role',
            },
        ),
        migrations.CreateModel(
            name='UserRoleShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user_id', models.IntegerField(db_index=True, help_text='用户id', verbose_name='用户id')),
                ('role_id', models.IntegerField(db_index=True, help_text='角色id', verbose_name='角色id')),
            ],
            options={
                'verbose_name': 'rbac_用户与角色关联表',
                'verbose_name_plural': 'rbac_用户与角色关联表',
                'db_table': 'rbac_user_role',
                'unique_together': {('role_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='UserPermissionShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('permission_id', models.IntegerField(db_index=True, help_text='对应权限内容表的id', verbose_name='对应权限内容表的id')),
                ('user_id', models.IntegerField(db_index=True, help_text='用户id', verbose_name='用户id')),
            ],
            options={
                'verbose_name': 'rbac_用户与权限关联表',
                'verbose_name_plural': 'rbac_用户与权限关联表',
                'db_table': 'rbac_user_permission',
                'unique_together': {('permission_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='UserGroupShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('group_id', models.IntegerField(db_index=True, help_text='用户组id', verbose_name='用户组id')),
                ('user_id', models.IntegerField(db_index=True, help_text='用户id', verbose_name='用户id')),
            ],
            options={
                'verbose_name': 'rbac_组与用户关联表',
                'verbose_name_plural': 'rbac_组与用户关联表',
                'db_table': 'rbac_group_user',
                'unique_together': {('group_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='RolePermissionShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('role_id', models.IntegerField(db_index=True, help_text='角色ID', verbose_name='角色ID')),
                ('permission_id', models.IntegerField(db_index=True, help_text='权限ID', verbose_name='权限ID')),
            ],
            options={
                'verbose_name': 'rbac_角色权限关联表',
                'verbose_name_plural': 'rbac_角色权限关联表',
                'db_table': 'rbac_role_permission',
                'unique_together': {('role_id', 'permission_id')},
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('permission_id', models.IntegerField(db_index=True, help_text='对应权限种类表中的ID', verbose_name='对应权限种类表中的ID')),
                ('permission_type', models.CharField(db_index=True, help_text='权限类型', max_length=64, verbose_name='权限类型')),
            ],
            options={
                'verbose_name': 'rbac_权限表',
                'verbose_name_plural': 'rbac_权限表',
                'db_table': 'rbac_permission',
                'unique_together': {('permission_id', 'permission_type')},
            },
        ),
        migrations.CreateModel(
            name='ModelOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('app_label', models.CharField(default='undefined', help_text='表所对应的app名称', max_length=128, verbose_name='表所对应的app名称')),
                ('op_name', models.CharField(help_text='操作名称', max_length=128, verbose_name='操作名称')),
                ('op_model_name', models.CharField(help_text='操作表的名称', max_length=128, verbose_name='操作表的名称')),
                ('description', models.TextField(help_text='操作的权限的描述', null=True, verbose_name='操作的权限的描述')),
                ('p_id', models.IntegerField(help_text='父操作ID', null=True, verbose_name='父操作ID')),
            ],
            options={
                'verbose_name': 'rbac_表操作权限',
                'verbose_name_plural': 'rbac_表操作权限',
                'db_table': 'rbac_model_operation',
                'unique_together': {('op_name', 'op_model_name')},
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('menu_name', models.CharField(help_text='菜单名称', max_length=128, verbose_name='菜单名称')),
                ('menu_url', models.CharField(help_text='菜单url', max_length=128, unique=True, verbose_name='菜单url')),
                ('menu_icon', models.CharField(help_text='菜单对应的vue-icon', max_length=128, null=True, verbose_name='菜单对应的Vue-icon')),
                ('menu_type', models.SmallIntegerField(default=0, help_text='菜单类型:0菜单 1按钮', verbose_name='菜单类型:0菜单 1按钮')),
                ('menu_view_path', models.CharField(help_text='菜单对应的page路径', max_length=128, null=True, verbose_name='菜单对应的page路径')),
                ('p_id', models.ForeignKey(help_text='父级菜单', null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.menu', verbose_name='父级菜单')),
            ],
            options={
                'verbose_name': 'rbac_菜单',
                'verbose_name_plural': 'rbac_菜单',
                'db_table': 'rbac_menu',
            },
        ),
        migrations.CreateModel(
            name='GroupRoleShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('group_id', models.IntegerField(db_index=True, help_text='用户组id', verbose_name='用户组id')),
                ('role_id', models.IntegerField(db_index=True, help_text='角色id', verbose_name='角色id')),
            ],
            options={
                'verbose_name': 'rbac_组与角色关联表',
                'verbose_name_plural': 'rbac_组与角色关联表',
                'db_table': 'rbac_group_role',
                'unique_together': {('role_id', 'group_id')},
            },
        ),
    ]
