# Generated by Django 4.0.4 on 2022-11-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissionShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('permission_id', models.IntegerField(db_index=True, help_text='权限id', verbose_name='权限id')),
                ('user_id', models.IntegerField(db_index=True, help_text='用户id', verbose_name='用户id')),
            ],
            options={
                'verbose_name': 'rbac_用户与权限关联表',
                'verbose_name_plural': 'rbac_用户与权限关联表',
                'db_table': 'rbac_user_permission',
            },
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(help_text='用户角色', max_length=128, unique=True, verbose_name='用户角色'),
        ),
    ]
