# Generated by Django 4.0.4 on 2022-11-10 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloperation',
            name='p_id',
            field=models.ForeignKey(help_text='父操作ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.modeloperation', verbose_name='父操作ID'),
        ),
    ]
