# Generated by Django 4.0.4 on 2022-11-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_userpermissionship_alter_role_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('op_name', models.CharField(help_text='操作名称', max_length=128, verbose_name='操作名称')),
                ('op_model_name', models.CharField(help_text='操作表的名称', max_length=128, verbose_name='操作表的名称')),
                ('description', models.TextField(help_text='操作的权限的描述', null=True, verbose_name='操作的权限的描述')),
                ('p_id', models.IntegerField(help_text='父操作ID', verbose_name='父操作ID')),
            ],
            options={
                'verbose_name': 'rbac_表操作权限',
                'verbose_name_plural': 'rbac_表操作权限',
                'db_table': 'rbac_model_operation',
            },
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
