# Generated by Django 4.0.4 on 2022-11-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_alter_modeloperation_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_route_name',
            field=models.CharField(help_text='路由名称', max_length=128, null=True, verbose_name='路由名称'),
        ),
    ]
