# Generated by Django 4.0.4 on 2022-11-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_menu_menu_route_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_icon',
            field=models.CharField(blank=True, help_text='菜单对应的vue-icon', max_length=128, null=True, verbose_name='菜单对应的Vue-icon'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_route_name',
            field=models.CharField(default=1, help_text='路由名称', max_length=128, verbose_name='路由名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_view_path',
            field=models.CharField(default=222, help_text='菜单对应的page路径', max_length=128, verbose_name='菜单对应的page路径'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modeloperation',
            name='description',
            field=models.TextField(blank=True, help_text='操作的权限的描述', null=True, verbose_name='操作的权限的描述'),
        ),
    ]
