# Generated by Django 4.0.4 on 2022-11-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_modeloperation_delete_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloperation',
            name='p_id',
            field=models.IntegerField(help_text='父操作ID', null=True, verbose_name='父操作ID'),
        ),
        migrations.AlterUniqueTogether(
            name='modeloperation',
            unique_together={('op_name', 'op_model_name')},
        ),
    ]
