# Generated by Django 4.0.4 on 2022-12-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_alter_menu_menu_icon_alter_menu_menu_route_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_descriptions',
            field=models.TextField(blank=True, help_text='角色描述', null=True, verbose_name='角色描述'),
        ),
    ]
