# Generated by Django 4.0.4 on 2022-11-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_alter_modeloperation_p_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grouproleship',
            unique_together={('role_id', 'group_id')},
        ),
        migrations.AlterUniqueTogether(
            name='menupermissionship',
            unique_together={('menu_id', 'permission_id')},
        ),
        migrations.AlterUniqueTogether(
            name='operationpermissionship',
            unique_together={('op_id', 'permission_id')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermissionship',
            unique_together={('role_id', 'permission_id')},
        ),
        migrations.AlterUniqueTogether(
            name='usergroupship',
            unique_together={('group_id', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='userpermissionship',
            unique_together={('permission_id', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='userroleship',
            unique_together={('role_id', 'user_id')},
        ),
    ]
