# Generated by Django 4.0.4 on 2022-11-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_alter_grouproleship_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='permission_type',
            field=models.CharField(db_index=True, help_text='权限类型', max_length=64, verbose_name='权限类型'),
        ),
        migrations.AlterUniqueTogether(
            name='permissions',
            unique_together={('permission_id', 'permission_type')},
        ),
    ]
