# Generated by Django 4.0.4 on 2022-11-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_alter_permissions_permission_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permissions',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='permission_id',
        ),
    ]
