# Generated by Django 4.0.4 on 2022-11-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_alter_permissions_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloperation',
            name='app_label',
            field=models.CharField(default='undefined', help_text='表所对应的app名称', max_length=128, verbose_name='表所对应的app名称'),
        ),
    ]
