# Generated by Django 4.0.4 on 2022-12-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('country_code', models.CharField(help_text='城市对应的高德地图里面的编码', max_length=32, unique=True, verbose_name='城市对应的高德地图里面的编码')),
                ('current_confirmed_count', models.IntegerField(default=0, help_text='新增确诊人数', verbose_name='新增确诊人数')),
                ('confirmed_count', models.IntegerField(default=0, help_text='确诊总人数', verbose_name='确诊总人数')),
                ('confirmed_count2', models.IntegerField(default=0, help_text='无症状确诊人数', verbose_name='无症状确诊人数')),
                ('cured_count', models.IntegerField(default=0, help_text='治愈人数', verbose_name='治愈人数')),
                ('dead_count', models.IntegerField(default=0, help_text='死亡人数', verbose_name='死亡人数')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('country_code', models.CharField(help_text='国家对应的高德地图里面的编码', max_length=32, unique=True, verbose_name='国家对应的高德地图里面的编码')),
                ('country_code_cn', models.CharField(help_text='国家名称中文', max_length=32, unique=True, verbose_name='国家名称中文')),
                ('country_code_en', models.CharField(help_text='国家名称英文', max_length=32, unique=True, verbose_name='国家名称英文')),
                ('current_confirmed_count', models.IntegerField(default=0, help_text='新增确诊人数', verbose_name='新增确诊人数')),
                ('confirmed_count', models.IntegerField(default=0, help_text='确诊总人数', verbose_name='确诊总人数')),
                ('confirmed_count2', models.IntegerField(default=0, help_text='无症状确诊人数', verbose_name='无症状确诊人数')),
                ('cured_count', models.IntegerField(default=0, help_text='治愈人数', verbose_name='治愈人数')),
                ('dead_count', models.IntegerField(default=0, help_text='死亡人数', verbose_name='死亡人数')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(help_text='政策名称', max_length=256, verbose_name='政策名称')),
                ('loc', models.CharField(help_text='发布地', max_length=256, verbose_name='发布地')),
                ('src', models.CharField(help_text='消息源', max_length=256, verbose_name='消息源')),
                ('url', models.CharField(help_text='消息源链接', max_length=256, verbose_name='消息源链接')),
                ('type', models.CharField(help_text='新闻类型', max_length=32, verbose_name='新闻类型')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(help_text='政策名称', max_length=256, verbose_name='政策名称')),
                ('loc', models.CharField(help_text='发布地', max_length=256, verbose_name='发布地')),
                ('src', models.CharField(help_text='消息源链接', max_length=256, verbose_name='消息源链接')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('country_code', models.CharField(help_text='省份对应的高德地图里面的编码', max_length=32, unique=True, verbose_name='省份对应的高德地图里面的编码')),
                ('current_confirmed_count', models.IntegerField(default=0, help_text='新增确诊人数', verbose_name='新增确诊人数')),
                ('confirmed_count', models.IntegerField(default=0, help_text='确诊总人数', verbose_name='确诊总人数')),
                ('confirmed_count2', models.IntegerField(default=0, help_text='无症状确诊人数', verbose_name='无症状确诊人数')),
                ('cured_count', models.IntegerField(default=0, help_text='治愈人数', verbose_name='治愈人数')),
                ('dead_count', models.IntegerField(default=0, help_text='死亡人数', verbose_name='死亡人数')),
            ],
        ),
    ]
