# Generated by Django 4.0.4 on 2022-12-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='confirmed_count2',
            new_name='confirmed_count_no_symptom',
        ),
    ]
