# Generated by Django 4.0.4 on 2022-12-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0002_rename_confirmed_count2_country_confirmed_count_no_symptom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country_code',
            new_name='city_code',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_code_cn',
            new_name='country_name_cn',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_code_en',
            new_name='country_name_en',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='country_code',
            new_name='province_code',
        ),
        migrations.RemoveField(
            model_name='city',
            name='confirmed_count2',
        ),
        migrations.RemoveField(
            model_name='country',
            name='confirmed_count_no_symptom',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='current_confirmed_count',
        ),
        migrations.RemoveField(
            model_name='province',
            name='confirmed_count2',
        ),
        migrations.AddField(
            model_name='city',
            name='city_name',
            field=models.CharField(default=1, help_text='城市名称', max_length=32, unique=True, verbose_name='城市名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='current_confirmed_count_no_symptom',
            field=models.IntegerField(default=0, help_text='新增无症状确诊人数', verbose_name='新增无症状确诊人数'),
        ),
        migrations.AddField(
            model_name='province',
            name='current_confirmed_count_no_symptom',
            field=models.IntegerField(default=0, help_text='新增无症状确诊人数', verbose_name='新增无症状确诊人数'),
        ),
        migrations.AddField(
            model_name='province',
            name='province_name',
            field=models.CharField(default=1, help_text='省份名称', max_length=32, unique=True, verbose_name='省份名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True, unique=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated',
            field=models.DateField(auto_now=True, db_index=True, unique=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='country',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True, unique=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated',
            field=models.DateField(auto_now=True, db_index=True, unique=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True, unique=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated',
            field=models.DateField(auto_now=True, db_index=True, unique=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True, unique=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='updated',
            field=models.DateField(auto_now=True, db_index=True, unique=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='province',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True, unique=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='province',
            name='updated',
            field=models.DateField(auto_now=True, db_index=True, unique=True, verbose_name='修改时间'),
        ),
    ]
