# Generated by Django 4.0.4 on 2023-01-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0003_rename_country_code_city_city_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(help_text='城市名称英文', max_length=32, null=True, unique=True, verbose_name='城市名称英文'),
        ),
        migrations.AddField(
            model_name='city',
            name='country_name_cn',
            field=models.CharField(default=1, help_text='国家名称中文', max_length=32, unique=True, verbose_name='国家名称中文'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='country_name_en',
            field=models.CharField(help_text='国家名称英文', max_length=32, null=True, unique=True, verbose_name='国家名称英文'),
        ),
        migrations.AddField(
            model_name='city',
            name='province_code',
            field=models.CharField(default=1, help_text='省份对应的高德地图里面的编码', max_length=32, unique=True, verbose_name='省份对应的高德地图里面的编码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='province_name',
            field=models.CharField(default=1, help_text='省份名称', max_length=32, unique=True, verbose_name='省份名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='province_name_en',
            field=models.CharField(help_text='省份名称英文', max_length=32, null=True, unique=True, verbose_name='省份名称英文'),
        ),
    ]
