# Generated by Django 4.0.4 on 2023-01-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0004_city_city_name_en_city_country_name_cn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市疫情统计', 'verbose_name_plural': '城市疫情统计'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '国家疫情统计', 'verbose_name_plural': '国家疫情统计'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '疫情新闻', 'verbose_name_plural': '疫情新闻'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': '防疫政策', 'verbose_name_plural': '防疫政策'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': '省份疫情统计', 'verbose_name_plural': '省份疫情统计'},
        ),
        migrations.AlterModelTable(
            name='city',
            table='covid19_city_data',
        ),
        migrations.AlterModelTable(
            name='country',
            table='covid19_country_data',
        ),
        migrations.AlterModelTable(
            name='news',
            table='covid19_news',
        ),
        migrations.AlterModelTable(
            name='policy',
            table='covid19_policy',
        ),
        migrations.AlterModelTable(
            name='province',
            table='covid19_province_data',
        ),
    ]
