# Generated by Django 4.0.4 on 2023-01-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0005_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '国家疫情统计', 'verbose_name_plural': '省份疫情统计'},
        ),
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(help_text='消息摘要', null=True, verbose_name='消息摘要'),
        ),
    ]
