# Generated by Django 4.0.4 on 2023-01-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0006_alter_country_options_news_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_code',
            field=models.CharField(help_text='城市对应的高德地图里面的编码', max_length=32, verbose_name='城市对应的高德地图里面的编码'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(help_text='城市名称', max_length=32, verbose_name='城市名称'),
        ),
        migrations.AlterField(
            model_name='city',
            name='province_code',
            field=models.CharField(help_text='省份对应的高德地图里面的编码', max_length=32, verbose_name='省份对应的高德地图里面的编码'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('city_name', 'created')},
        ),
    ]
