# Generated by Django 4.0.4 on 2023-01-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0007_alter_city_city_code_alter_city_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated',
            field=models.DateField(auto_now=True, db_index=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='country',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated',
            field=models.DateField(auto_now=True, db_index=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated',
            field=models.DateField(auto_now=True, db_index=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='updated',
            field=models.DateField(auto_now=True, db_index=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='province',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='province',
            name='updated',
            field=models.DateField(auto_now=True, db_index=True, verbose_name='修改时间'),
        ),
    ]
