# Generated by Django 4.0.4 on 2023-01-19 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0009_alter_city_city_name_en_alter_city_country_name_cn_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
    ]
