# Generated by Django 4.0.4 on 2023-01-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0010_alter_city_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(help_text='城市名称', max_length=64, verbose_name='城市名称'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(help_text='城市名称英文', max_length=64, null=True, verbose_name='城市名称英文'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country_name_cn',
            field=models.CharField(help_text='国家名称中文', max_length=64, verbose_name='国家名称中文'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country_name_en',
            field=models.CharField(help_text='国家名称英文', max_length=64, null=True, verbose_name='国家名称英文'),
        ),
        migrations.AlterField(
            model_name='city',
            name='province_name',
            field=models.CharField(help_text='省份名称', max_length=64, verbose_name='省份名称'),
        ),
        migrations.AlterField(
            model_name='city',
            name='province_name_en',
            field=models.CharField(help_text='省份名称英文', max_length=64, null=True, verbose_name='省份名称英文'),
        ),
    ]
