# Generated by Django 4.0.4 on 2023-01-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WechatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('msg_id', models.BigIntegerField(help_text='消息id,64位整型', unique=True, verbose_name='消息id,64位整型')),
                ('msg_to', models.CharField(help_text='开发者微信号', max_length=256, verbose_name='开发者微信号')),
                ('msg_from', models.CharField(help_text='发送方帐号(一个OpenID)', max_length=256, verbose_name='发送方帐号(一个OpenID)')),
                ('create_time', models.BigIntegerField(help_text='消息创建时间', verbose_name='消息创建时间')),
                ('msg_type', models.CharField(help_text='消息类型(文本:text,图片:image,语音:voice,视频:video,小视频:shortvideo,地理位置:location,链接:link)', max_length=32, verbose_name='消息类型')),
                ('content', models.TextField(help_text='消息内容', verbose_name='消息内容')),
                ('msg_data_id', models.CharField(help_text='消息的数据ID(消息如果来自文章时才有)', max_length=256, verbose_name='消息的数据ID')),
                ('idx', models.IntegerField(help_text='多图文时第几篇文章，从1开始（消息如果来自文章时才有）', verbose_name='多图文时第几篇文章')),
                ('media_id', models.CharField(help_text='语音消息媒体id，可以调用获取临时素材接口拉取数据', max_length=256, verbose_name='语音/视频消息媒体id，可以调用获取临时素材接口拉取数据')),
                ('voice_format', models.CharField(help_text='语音格式', max_length=32, verbose_name='语音格式')),
                ('voice_recognition', models.TextField(help_text='语音识别结果(UTF-8编码)', verbose_name='语音识别结果')),
                ('thumb_media_id', models.CharField(help_text='视频消息缩略图的媒体id,可以调用多媒体文件下载接口拉取数据。', max_length=256, verbose_name='视频消息缩略图的媒体id,可以调用多媒体文件下载接口拉取数据。')),
                ('link_title', models.CharField(help_text='链接消息标题', max_length=256, verbose_name='链接消息标题')),
                ('link_description', models.TextField(help_text='链接消息描述', verbose_name='链接消息描述')),
                ('link_url', models.URLField(help_text='消息链接url', verbose_name='消息链接url')),
            ],
            options={
                'verbose_name': '微信公众号消息记录',
                'verbose_name_plural': '微信公众号消息记录',
                'db_table': 'wechat_public_count_message',
            },
        ),
    ]
