# Generated by Django 4.0.4 on 2023-01-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatmessage',
            name='content',
            field=models.TextField(help_text='消息内容', null=True, verbose_name='消息内容'),
        ),
        migrations.AlterField(
            model_name='wechatmessage',
            name='idx',
            field=models.IntegerField(help_text='多图文时第几篇文章，从1开始（消息如果来自文章时才有）', null=True, verbose_name='多图文时第几篇文章'),
        ),
        migrations.AlterField(
            model_name='wechatmessage',
            name='link_description',
            field=models.TextField(help_text='链接消息描述', null=True, verbose_name='链接消息描述'),
        ),
        migrations.AlterField(
            model_name='wechatmessage',
            name='link_title',
            field=models.CharField(help_text='链接消息标题', max_length=256, null=True, verbose_name='链接消息标题'),
        ),
        migrations.AlterField(
            model_name='wechatmessage',
            name='link_url',
            field=models.URLField(help_text='消息链接url', null=True, verbose_name='消息链接url'),
        ),
        migrations.AlterField(
            model_name='wechatmessage',
            name='media_id',
            field=models.CharField(help_text='语音消息媒体id，可以调用获取临时素材接口拉取数据', max_length=256, null=True, verbose_name='语音/视频消息媒体id，可以调用获取临时素材接口拉取数据'),
        ),
        migrations.AlterField(
            model_name='wechatmessage',
            name='msg_data_id',
            field=models.CharField(help_text='消息的数据ID(消息如果来自文章时才有)', max_length=256, null=True, verbose_name='消息的数据ID'),
        ),
        migrations.AlterField(
            model_name='wechatmessage',
            name='thumb_media_id',
            field=models.CharField(help_text='视频消息缩略图的媒体id,可以调用多媒体文件下载接口拉取数据。', max_length=256, null=True, verbose_name='视频消息缩略图的媒体id,可以调用多媒体文件下载接口拉取数据。'),
        ),
        migrations.AlterField(
            model_name='wechatmessage',
            name='voice_format',
            field=models.CharField(help_text='语音格式', max_length=32, null=True, verbose_name='语音格式'),
        ),
        migrations.AlterField(
            model_name='wechatmessage',
            name='voice_recognition',
            field=models.TextField(help_text='语音识别结果(UTF-8编码)', null=True, verbose_name='语音识别结果'),
        ),
    ]
