# Generated by Django 4.0.4 on 2023-01-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_alter_wechatmessage_content_alter_wechatmessage_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatmessage',
            name='msg_id',
            field=models.BigIntegerField(help_text='消息id,64位整型', null=True, verbose_name='消息id,64位整型'),
        ),
    ]
