# Generated by Django 4.0.4 on 2023-01-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_alter_wechatmessage_msg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatmessage',
            name='event',
            field=models.CharField(help_text='事件类型', max_length=32, null=True, verbose_name='事件类型'),
        ),
        migrations.AddField(
            model_name='wechatmessage',
            name='event_key',
            field=models.CharField(help_text='事件KEY值,qrscene_为前缀,后面为二维码的参数值,或者是菜单的key', max_length=256, null=True, verbose_name='事件KEY值'),
        ),
        migrations.AddField(
            model_name='wechatmessage',
            name='has_reply',
            field=models.BooleanField(default=False, help_text='是否已经回复', verbose_name='是否已经回复'),
        ),
        migrations.AddField(
            model_name='wechatmessage',
            name='latitude',
            field=models.CharField(help_text='地理位置纬度', max_length=32, null=True, verbose_name='地理位置纬度'),
        ),
        migrations.AddField(
            model_name='wechatmessage',
            name='longitude',
            field=models.CharField(help_text='地理位置经度', max_length=32, null=True, verbose_name='地理位置经度'),
        ),
        migrations.AddField(
            model_name='wechatmessage',
            name='precision',
            field=models.CharField(help_text='地理位置精度', max_length=32, null=True, verbose_name='地理位置精度'),
        ),
        migrations.AddField(
            model_name='wechatmessage',
            name='ticket',
            field=models.CharField(help_text='二维码的ticket，可用来换取二维码图片', max_length=256, null=True, verbose_name='二维码ticket'),
        ),
    ]
