# Generated by Django 4.0.4 on 2023-02-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_wechatmessage_event_wechatmessage_event_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatmessage',
            name='reply_content',
            field=models.TextField(default=False, help_text='回复内容', null=True, verbose_name='回复内容'),
        ),
    ]
